import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";
import { links } from "@/components/FloatingDock";
import { FloatingDock } from "@/components/ui/floating-dock";
import { Analytics } from "@vercel/analytics/next"

const space_grotesk = Space_Grotesk({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Praneet's Portfolio",
  description: "Generated by create next app",
};

export const viewport = {
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <head>
          <meta name="viewport" content="width=device-width" />
        </head>
        <body className={`${space_grotesk.className} antialiased min-h-screen`}>
          <main className="flex flex-col p-2 md:p-4 md:pl-12 md:pr-12">{children}</main>
          <div className="hidden md:block">
            <FloatingDock items={links}/>
          </div>
          <div className="md:hidden">
            <Footer />
          </div>
          <Analytics />
        </body>
      </html>
    </ThemeProvider>
  );
}
